<h3>Conditions and Branching</h3>

In [11]:
a=2

In [12]:
a==3

False

In [13]:
a>4

False

In [14]:
a<=3

True

In [15]:
if(a==4):
    
    print("Vive Mimi")
    
print("hugo")

hugo


In [16]:
if(a>3):
    
    print("a")
    
elif(a>2):
    
    print("b")
    
else:
    print("$")

$


In [17]:
not(a==4)

True

In [18]:
if(a==4)or(a==3):
    
    print("abc")
    
elif(a>1)and(a<=2):
    
    print("def")

def


In [19]:
a!=2

False

In [20]:
'c' >= 'B'

True

In [21]:
'F'!="P"

True

<h3> Loops </h3>

In [22]:
range(3)

range(0, 3)

In [23]:
range(5,9)

range(5, 9)

In [24]:
list(range(5,9))

[5, 6, 7, 8]

In [25]:
dates = [1982,1980,1973]
N = len(dates)

for i in range(N):
    print(dates[i])  

1982
1980
1973


In [26]:
for i in dates:
    print(i)

1982
1980
1973


In [27]:
squares=['red', 'yellow', 'green', 'purple', 'blue']

for i, square in enumerate(squares):
    print(i, square)

0 red
1 yellow
2 green
3 purple
4 blue


In [28]:
squares=['red', 'yellow', 'green', 'purple', 'blue']

for i in range(0,5):
    
    squares[i] = "white"
    
    print(i, squares[i])

0 white
1 white
2 white
3 white
4 white


In [29]:
squares=['red', 'yellow', 'green', 'purple', 'blue']

i = len(squares)

for i in range(i):
    
    squares[i] = "white"
    
    print(i, squares[i])

0 white
1 white
2 white
3 white
4 white


In [30]:
squares=['red', 'yellow', 'green', 'purple', 'blue']

for i in squares:
    
    print(i)

red
yellow
green
purple
blue


In [31]:
dates = [1982, 1980, 1973, 2000]

i = 0
year = dates[0]

while(year != 1973):    
    print(year)
    i = i + 1
    year = dates[i]
    

print("It took ", i ,"repetitions to get out of loop.")

1982
1980
It took  2 repetitions to get out of loop.


In [32]:
dates = [1982, 1980, 1973, 2000]

i = 0 
year = dates[0]

while(year!=2000):
    print(year)
    i = i + 1
    year = dates[i]
    
print("Viva la vida")

1982
1980
1973
Viva la vida


In [33]:
for i in range(-5,6):
    print(i)

-5
-4
-3
-2
-1
0
1
2
3
4
5


In [34]:
Genres=[ 'rock', 'R&B', 'Soundtrack', 'R&B', 'soul', 'pop']

for i in Genres:
    print(i)

rock
R&B
Soundtrack
R&B
soul
pop


In [35]:
squares=['red', 'yellow', 'green', 'purple', 'blue']

for bouyachaka in squares:
    print(bouyachaka)

red
yellow
green
purple
blue


In [36]:
PlayListRatings = [10, 9.5, 10, 8, 7.5, 5, 10, 10]

i=0

Ratings = PlayListRatings[0]

while(Ratings>6):
    print(Ratings)
    i = i + 1
    Ratings = PlayListRatings[i]
    
print("ok")

10
9.5
10
8
7.5
ok


In [37]:
squares = ['orange', 'orange', 'purple', 'blue ', 'orange']
new_squares = []

i = 0

while(squares[i]=="orange"):
    new_squares.append("orange")
    i = i + 1

print(new_squares)

['orange', 'orange']


<h3> Functions </h3>

In [38]:
def add(a,b):
    return(a+b)

In [39]:
add(1394,395)

1789

In [40]:
def multiply(a,b):
    return(a*b)

In [41]:
multiply(3,5)

15

In [42]:
list = [1,3,7,9,10]

In [43]:
tuple(list)

(1, 3, 7, 9, 10)

In [44]:
len(list)

5

In [45]:
sum(list)

30

In [46]:
sorted(list)

[1, 3, 7, 9, 10]

In [47]:
print(list)

[1, 3, 7, 9, 10]


In [48]:
def ope(a):
    "ope is an example of function"
    c = 100
    b = a/c
    return (b)

In [49]:
ope(7)

0.07

In [50]:
help(ope)

Help on function ope in module __main__:

ope(a)
    ope is an example of function



In [51]:
multiply(2,"papi")

'papipapi'

In [52]:
def ML():
    print("MJ")
    return(None)

In [53]:
ML()

MJ


In [54]:
add("Je suis"," con")

'Je suis con'

In [55]:
def type_of_album(artist, album, year_released):
    
    print(artist, album, year_released)
    if year_released > 1980:
        return "Modern"
    else:
        return "Oldie"
    
x = type_of_album("Michael Jackson", "Thriller", 1980)
print(x)

Michael Jackson Thriller 1980
Oldie


In [56]:
def PrintList(the_list):
    for element in the_list:
        print(element)

In [57]:
the_list = [3, "o", 67, "EIRI"]

PrintList(the_list)

3
o
67
EIRI


In [58]:
def isGoodRating(rating=4): 
    if(rating < 7):
        print("this album sucks it's rating is",rating)
        
    else:
        print("this album is good its rating is",rating)

In [59]:
isGoodRating(4)

this album sucks it's rating is 4


In [60]:
isGoodRating(10)

this album is good its rating is 10


In [61]:
artist = "Michael Jackson"
internal_var1 = artist
def printer1(artist):
    print(artist, "is an artist")
    
printer1(artist)

Michael Jackson is an artist


In [62]:
printer1(internal_var1)

Michael Jackson is an artist


In [63]:
artist = "Michael Jackson"

def printer(artist):
    global internal_var 
    internal_var= "Whitney Houston"
    print(artist,"is an artist")

printer(artist) 
printer(internal_var)

Michael Jackson is an artist
Whitney Houston is an artist


In [64]:
myFavouriteBand = "AC/DC"

def getBandRating(bandname):
    if bandname == myFavouriteBand:
        return 10.0
    else:
        return 0.0

print("AC/DC's rating is:", getBandRating("AC/DC"))
print("Deep Purple's rating is:",getBandRating("Deep Purple"))
print("My favourite band is:", myFavouriteBand)

AC/DC's rating is: 10.0
Deep Purple's rating is: 0.0
My favourite band is: AC/DC


In [65]:
myFavouriteBand = "AC/DC"

def getBandRating(bandname):
    myFavouriteBand = "Deep Purple"
    if bandname == myFavouriteBand:
        return 10.0
    else:
        return 0.0

print("AC/DC's rating is:",getBandRating("AC/DC"))
print("Deep Purple's rating is: ",getBandRating("Deep Purple"))
print("My favourite band is:",myFavouriteBand)

AC/DC's rating is: 0.0
Deep Purple's rating is:  10.0
My favourite band is: AC/DC


In [66]:
def printAll(*args): # All the arguments are 'packed' into args which can be treated like a tuple
    print("No of arguments:", len(args)) 
    for argument in args:
        print(argument)
#printAll with 3 arguments
printAll('Horsefeather','Adonis','Bone')
#printAll with 4 arguments
printAll('Sidecar','Long Island','Mudslide','Carriage')

No of arguments: 3
Horsefeather
Adonis
Bone
No of arguments: 4
Sidecar
Long Island
Mudslide
Carriage


In [67]:
def printDictionary(**args):
    for key in args:
        print(key + " : " + args[key])

printDictionary(Country='Canada',Province='Ontario',City='Toronto')

Country : Canada
Province : Ontario
City : Toronto


In [68]:
def addItems(list):
    list.append("Three")
    list.append("Four")

myList = ["One","Two"]

addItems(myList)

myList
    

['One', 'Two', 'Three', 'Four']

<h3> Exception Handling </h3>

In [69]:
a = 1/0

ZeroDivisionError: division by zero

In [70]:
a = 1/"MJ"

TypeError: unsupported operand type(s) for /: 'int' and 'str'

In [73]:
a = b + 1

NameError: name 'b' is not defined

In [ ]:
a = [2,3,6,7]
a[7]

In [ ]:
try:
    a = b + 1
except:
    print("there is an error")
else:
    print(a)
finally:
    print("process completed")

In [ ]:
try:
    b = 3
    a = b + 1
except:
    print("there is an error")
else:
    print(a)
finally:
    print("process completed")

In [ ]:
try:
    b = input()
    a = b + 1
except:
    print("there is an error")
else:
    print(a)
finally:
    print("process completed")

In [ ]:
try:
    b = input("select b variable")
    a = b + 1
except:
    print("there is an error")
else:
    print(a)
finally:
    print("process completed")

In [ ]:
try:
    b = int(input("select b variable"))
    a = b + 1
except:
    print("there is an error")
else:
    print(a)
finally:
    print("process completed")

In [ ]:
try:
    b = int(input("select b variable"))
    c = int(input("select c variable"))
    a = (b + 1) / c
except ValueError:
    print("there is a value error")
except ZeroDivisionError:
    print("there is a zerodiv error")
else:
    print(a)
finally:
    print("process completed")

<h3> Objects and classes </h3>

In [ ]:
class Circle(object):
    
    def __init__(self,radius,color):
        self.radius = radius;
        self.color = color;
    
    def add_radius(self,r):
        self.radius = self.radius + r
        return(self.radius)

In [ ]:
C1 = Circle(10,"red")

In [ ]:
C1.color

In [ ]:
C1.radius

In [ ]:
C1.color = "blue"
C1.color

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline  

In [ ]:
class Circle(object):
    
    # Constructor
    def __init__(self, radius=3, color='blue'):
        self.radius = radius
        self.color = color 
    
    # Method
    def add_radius(self, r):
        self.radius = self.radius + r
        return(self.radius)
    
    # Method
    def drawCircle(self):
        plt.gca().add_patch(plt.Circle((0, 0), radius=self.radius, fc=self.color))
        plt.axis('scaled')
        plt.show()  

In [ ]:
C1 = Circle(10,"red")

In [ ]:
dir(C1)

In [ ]:
C1.drawCircle()

In [ ]:
B1 = Circle(13)

In [71]:
B1.radius

NameError: name 'B1' is not defined

In [ ]:
B1.color

In [ ]:
B1.drawCircle()

In [ ]:
dir(B1)

<h3> Reading files with open </h3>

In [67]:
import urllib.request
url = 'https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%204/data/example1.txt'
filename = 'Example1.txt'
urllib.request.urlretrieve(url, filename)

('Example1.txt', <http.client.HTTPMessage at 0x7fbc89370880>)

In [68]:
example1 = "Example1.txt"
file1 = open(example1, "r")

In [69]:
file1.name

'Example1.txt'

In [70]:
file1.mode

'r'

In [71]:
FileContent = file1.read()
FileContent

'This is line 1 \nThis is line 2\nThis is line 3'

In [72]:
with open(example1, "r") as file1:
    FileContent = file1.read()
    print(FileContent)

This is line 1 
This is line 2
This is line 3


In [73]:
file1.closed

True

In [74]:
print(FileContent)

This is line 1 
This is line 2
This is line 3


In [75]:
with open(example1, "r") as file1:
    print(file1.read(4))
    print(file1.read(5))
    print(file1.read(1))
    print(file1.read(7))

This
 is l
i
ne 1 
T


In [76]:
with open(example1, "r") as file1:
    print("first line: " + file1.readline())

first line: This is line 1 



In [77]:
with open(example1, "r") as file1:
    print(file1.readline(5))

This 


In [78]:
with open(example1, "r") as file1:
    print(file1.readlines())

['This is line 1 \n', 'This is line 2\n', 'This is line 3']


In [79]:
with open(example1,"r") as file1:
        i = 0;
        for line in file1:
            print("Iteration", str(i), ": ", line)
            i = i + 1

Iteration 0 :  This is line 1 

Iteration 1 :  This is line 2

Iteration 2 :  This is line 3


In [80]:
with open(example1,"r") as file1:
        i = 0;
        for line in file1:
            print("Iteration", str(i), ": ", line)
            i = i + 1

Iteration 0 :  This is line 1 

Iteration 1 :  This is line 2

Iteration 2 :  This is line 3


<h3> Writing files with open </h3>

TBC

<h3> Pandas </h3>

In [84]:
print("The coursera link doesn't work so I will go on Youtube for training (20min training from Machine Learnia)")

The coursera link doesn't work so I will go on Youtube for training (20min training from Machine Learnia)


In [85]:
#exemple of titanic
import pandas as pd
data = pd.read_excel("titanic3 (3).xls")

In [86]:
print(data.shape)

(1309, 14)


In [87]:
data.head()

pclass  survived                                             name     sex  \
0       1         1                    Allen, Miss. Elisabeth Walton  female   
1       1         1                   Allison, Master. Hudson Trevor    male   
2       1         0                     Allison, Miss. Helen Loraine  female   
3       1         0             Allison, Mr. Hudson Joshua Creighton    male   
4       1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female   

       age  sibsp  parch  ticket      fare    cabin embarked boat   body  \
0  29.0000      0      0   24160  211.3375       B5        S    2    NaN   
1   0.9167      1      2  113781  151.5500  C22 C26        S   11    NaN   
2   2.0000      1      2  113781  151.5500  C22 C26        S  NaN    NaN   
3  30.0000      1      2  113781  151.5500  C22 C26        S  NaN  135.0   
4  25.0000      1      2  113781  151.5500  C22 C26        S  NaN    NaN   

                         home.dest  
0                     St Louis, MO  
1  Montreal, PQ / Chesterville, ON  
2  Montreal, PQ / Chesterville, ON  
3  Montreal, PQ / Chesterville, ON  
4  Montreal, PQ / Chesterville, ON

In [88]:
print(data.shape)

(1309, 14)


In [89]:
data = data.drop(["name","sibsp","parch","ticket","fare","cabin","body","embarked","boat","home.dest"], axis=1)

In [90]:
data.head()

pclass  survived     sex      age
0       1         1  female  29.0000
1       1         1    male   0.9167
2       1         0  female   2.0000
3       1         0    male  30.0000
4       1         0  female  25.0000

In [91]:
data.describe()

pclass     survived          age
count  1309.000000  1309.000000  1046.000000
mean      2.294882     0.381971    29.881135
std       0.837836     0.486055    14.413500
min       1.000000     0.000000     0.166700
25%       2.000000     0.000000    21.000000
50%       3.000000     0.000000    28.000000
75%       3.000000     1.000000    39.000000
max       3.000000     1.000000    80.000000

In [92]:
#There are some missing ages 
#Two solution: eliminate or replace 

data = data.dropna(axis=0)

In [93]:
data.shape

(1046, 4)

In [94]:
data.describe()

pclass     survived          age
count  1046.000000  1046.000000  1046.000000
mean      2.207457     0.408222    29.881135
std       0.841497     0.491740    14.413500
min       1.000000     0.000000     0.166700
25%       1.000000     0.000000    21.000000
50%       2.000000     0.000000    28.000000
75%       3.000000     1.000000    39.000000
max       3.000000     1.000000    80.000000

In [95]:
data['pclass'].value_counts()

3    501
1    284
2    261
Name: pclass, dtype: int64

In [96]:
data.groupby(['sex']).mean()

pclass  survived        age
sex                                  
female  2.048969  0.752577  28.687071
male    2.300912  0.205167  30.585233

In [97]:
data.groupby(['sex','pclass']).mean()

survived        age
sex    pclass                     
female 1       0.962406  37.037594
       2       0.893204  27.499191
       3       0.473684  22.185307
male   1       0.350993  41.029250
       2       0.145570  30.815401
       3       0.169054  25.962273

In [98]:
data = data.set_index('age')
data['survived']

age
29.0000    1
0.9167     1
2.0000     0
30.0000    0
25.0000    0
          ..
45.5000    0
14.5000    0
26.5000    0
27.0000    0
29.0000    0
Name: survived, Length: 1046, dtype: int64

In [99]:
#Dataframe => dictionnaire qui contient des series 

In [100]:
data = pd.read_excel("titanic3 (3).xls")
data['age'][3:9]

3    30.0
4    25.0
5    48.0
6    63.0
7    39.0
8    53.0
Name: age, dtype: float64

In [104]:
data[data['age']<18]['pclass'].value_counts()

3    106
2     33
1     15
Name: pclass, dtype: int64

In [105]:
data[data['age']<18].groupby(['survived','pclass'])

In [106]:
data.iloc[0,0]
#Exactement comme dans numpy mais avec iloc (pour les rows)

1

In [107]:
data.iloc[0:4,5:6]

sibsp
0      0
1      1
2      1
3      1

In [108]:
data.loc[0:2,['age']]
#comme iloc mais sur les colonnes

age
0  29.0000
1   0.9167
2   2.0000

In [127]:
#Exercise
Cat0 = data[data['age']<20]['survived'].value_counts()
print(Cat0)

0    119
1    106
Name: survived, dtype: int64


In [128]:
b = data[data['age']<30]['survived'].value_counts()
print(b)

0    336
1    233
Name: survived, dtype: int64


In [129]:
Cat1 = b - Cat0
print(Cat1)

0    217
1    127
Name: survived, dtype: int64


In [132]:
Cat2 = data[data['age']>30]['survived'].value_counts()
print(Cat2)

0    258
1    179
Name: survived, dtype: int64


<h3> Numpy </h3>

In [1]:
import numpy as np

a = np.array([1,2,6,9,2])

a

array([1, 2, 6, 9, 2])

In [3]:
a.sort()

a

array([1, 2, 2, 6, 9])

In [6]:
a.mean()

4.0

In [8]:
a.max()

9

In [9]:
a[0]

1

In [10]:
a[3:4]

array([6])

In [11]:
a[3]=4

In [12]:
a

array([1, 2, 2, 4, 9])

In [20]:
print("The coursera link doesn't work so I will go on Youtube for training (30min training from Python Engineer)")

The coursera link doesn't work so I will go on Youtube for training (30min training from Python Engineer)


In [21]:
np.__version__

'1.19.2'

In [22]:
a = np.array([1,2,3,4,5])

In [28]:
print(a)
print(a.shape)
print(a.dtype)
print(a.ndim)
print(a.size)
print(a.itemsize)

[1 2 3 4 5]
(5,)
int64
1
5
8


In [30]:
#Some basics operations

print(a[0])
a[0] = 2
print(a)

b = a * np.array([1,2,3,4,5])
print(b)
print(b.sum())

2
[2 2 3 4 5]
[ 2  4  9 16 25]
56


In [31]:
#Difference between list and array

L = [1,2,3,4,5]
print(L)

print(a)

print(2*L)

print(2*a)

[1, 2, 3, 4, 5]
[2 2 3 4 5]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 4  4  6  8 10]


In [41]:
#dot product 
a = np.array([1,2])
b = np.array([3,4])

#Method1
dot = 0

for i in range(len(a)):
    dot += a[i] * b[i]
print(dot)

#Method2
dot = np.dot(a,b)

print(dot)

#Method3
dot = a.dot(b)

print(dot)

#Method4
dot = a @ b
print(dot)

11
11
11
11


In [43]:
#Difference between List and Array 

from timeit import default_timer as timer
a = np.random.randn(1000)
b = np.random.randn(1000)
A = list(a)
B = list(b)
T = 1000

def dot1():
    dot = 0
    for i in range (len(A)):
        dot += A[i] * B[i]
    return dot

def dot2(): 
    return np.dot(a,b)

start = timer()
for t in range(T):
    dot1()
end = timer()
t1 = end-start

start = timer()
for t in range(T):
    dot2()
end = timer()
t2 = end-start

print("Time with lists:", t1)
print("Time with array:", t2)
print("Ratio", t1/t2)

Time with lists: 0.23998449999999139
Time with array: 0.02950791700004629
Ratio 8.132885150775465


In [45]:
#Multidimensional arrays (nd)

a = np.array([[1,2],[3,4]])
print(a)
print(a.shape)

[[1 2]
 [3 4]]
(2, 2)


In [47]:
#Indexing and Slicing 

print(a[0])
print(a[0][1])
print(a[1,0])

print(a[:,0])
print(a[0,:])

[1 2]
2
3
[1 3]
[1 2]


In [48]:
#transpose
print(a.T)

[[1 3]
 [2 4]]


In [59]:
#matrix multiplication

b = np.array([[3,4],[5,6]])
print(b)
c = a.dot(b)
print(c)
d = a * b
print(d)

[[3 4]
 [5 6]]
[[13 16]
 [29 36]]
[[ 3  8]
 [15 24]]


In [60]:
b = np.array([[2,3,4],[4,5,6]])
#c = a.dot(b.T) => doesn't work => Pay attention to the shape
#inner dimensions must match 

In [61]:
#determinant(linear algebra)

print(c)
c = np.linalg.det(a)
print(c)

[[13 16]
 [29 36]]
-2.0000000000000004


In [62]:
#inverse

print(c)
c = np.linalg.inv(a)
print(c)

-2.0000000000000004
[[-2.   1. ]
 [ 1.5 -0.5]]


In [66]:
#diag
print(a)
c = np.diag(a)
print(c)

c = np.diag([1,4])
print(c)

[[1 2]
 [3 4]]
[1 4]
[[1 0]
 [0 4]]


In [69]:
#Classic indexing and slicing

a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)

b = a[0,1]
print(b)

row0 = a[0,:]
print(row0)

col0 = a[:,0]
print(col0)

slicea = a[0:2,1:3]
print(slicea)

last = a[-1,-1]
print(last)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2
[1 2 3 4]
[1 5 9]
[[2 3]
 [6 7]]
12


In [80]:
#Boolean indexing 

a = np.array([[1,2],[3,4],[5,6]])
print(a)

boo_idx = a > 2
print(boo_idx)

print(a[boo_idx])

print(a>2)

print(a[a>2])

[[1 2]
 [3 4]
 [5 6]]
[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]


In [81]:
#where

b = np.where(a>2, a, -1)
print(b)

[[-1 -1]
 [ 3  4]
 [ 5  6]]


In [86]:
#fancy indexing 
a = np.array([2,54,76,34,65])
b = a[[0,2,4]]
print(b)

[ 2 76 65]


In [87]:
even= np.argwhere(a%2==0).flatten()
print(even)
a_even = a[even]
print(a_even)

[0 1 2 3]
[ 2 54 76 34]


In [90]:
#reshaping

a = np.arange(1,7)
print(a)

b = a.reshape((2,3))

[1 2 3 4 5 6]


In [92]:
#newaxis

print(a)
print(a.shape)

[1 2 3 4 5 6]
(6,)


In [94]:
d = a[np.newaxis, :]
print(d)
print(d.shape)

#useful for ML

[[1 2 3 4 5 6]]
(1, 6)


In [95]:
e = a[:,np.newaxis]
print(e)
print(e.shape)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
(6, 1)


In [103]:
#Broadcasting & Concatenation

a = np.array([[1,2],[3,4]])
b = np.array([[5,6]])
print(a)
print(b)

#Broadcasting
c = a + b
print(c)

#Concatenation
c = np.concatenate((a,b),axis=0)
print(c)

c = np.concatenate((a,b.T),axis=1)
print(c)

[[1 2]
 [3 4]]
[[5 6]]
[[ 6  8]
 [ 8 10]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 5]
 [3 4 6]]


In [109]:
#hstack : sequence horizontally 

a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

#be careful hstack or vstack need a tuple => ()
c = np.hstack((a,b)) 
print(c)

a = np.array([[1,2,3,4],[5,6,7,8]])
b = np.array([[1,2,3,4],[5,6,7,8]])

c = np.hstack((a,b))
print(c)

[1 2 3 4 5 6 7 8]
[[1 2 3 4 1 2 3 4]
 [5 6 7 8 5 6 7 8]]


In [110]:
#vstack : sequence verticaly

a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

#be careful hstack or vstack need a tuple => ()
c = np.vstack((a,b)) 
print(c)

a = np.array([[1,2,3,4],[5,6,7,8]])
b = np.array([[1,2,3,4],[5,6,7,8]])

c = np.vstack((a,b))
print(c)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]
 [5 6 7 8]]


In [113]:
#Functions and Axis

a = np.array([[7,8,9,10,11,12,13],[17,18,19,20,21,22,23]])
print(a.sum())
print(a.sum(axis=None))
print(a.sum(axis=0))
print(a.sum(axis=1))

#Pay attention to apply the correct axis, 0 for columns and 1 for rows

210
210
[24 26 28 30 32 34 36]
[ 70 140]


In [115]:
print(a.mean())
print(a.mean(axis=None))
print(a.mean(axis=0))
print(a.mean(axis=1))

#some more : std, var, min, max

15.0
15.0
[12. 13. 14. 15. 16. 17. 18.]
[10. 20.]


In [119]:
#Datatype

x = np.array([1,2])
print(x.dtype)

x = np.array([1.0,2.0])
print(x.dtype)

x = np.array([1,2],dtype = np.int64)
print(x.dtype)

x = np.array([1,2],dtype = np.float64)
print(x.dtype)

int64
float64
int64
float64


In [121]:
#Copying

a = np.array([1,2,3])
b = a
b[0] = 42 #Be careful it will also modify a !

print(a)
print(b)

[42  2  3]
[42  2  3]


In [123]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 42

print(a)
print(b)

[1 2 3]
[42  2  3]


In [132]:
#Generating arrays

a = np.zeros((2,3)) #tuple size
print(a)

a = np.ones((2,3))
print(a)

c = np.full((3,3),5.0)
print(c)

e = np.arange(10)
print(e)

f = np.linspace(0,10,5)
print(f)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]
[0 1 2 3 4 5 6 7 8 9]
[ 0.   2.5  5.   7.5 10. ]


In [134]:
#Random numbers

a = np.random.random((3,2)) #tuple size #0-1 distribution
print(a)

b = np.random.randn(3,2) #only one () #normal distribution
print(b)

[[0.77111212 0.16575641]
 [0.25462572 0.88020772]
 [0.31450166 0.72472493]]
[[ 0.09628736  0.35715141]
 [ 0.48235287  0.54237509]
 [ 1.50553578 -0.29028586]]


In [140]:
c = np.random.randn(1000)
print(c.mean(), c.var(), c.std())

d = np.random.randn(10,3)
print(d)
print(d.mean())

0.020296226925533553 1.018016947258179 1.008968258796172
[[-0.1868688   1.02546707 -0.70884695]
 [ 0.39666726 -0.35721581  2.35386977]
 [ 0.36069798  1.47399282 -0.08477921]
 [-1.93555637 -0.60749986 -0.60165561]
 [ 0.81029989 -0.46708129 -0.37460305]
 [-2.71984624 -0.44492044  0.63695241]
 [ 0.1298873  -0.08130244  0.05948779]
 [-1.13709736  0.41687522  0.55031344]
 [-1.94607602 -1.24337414  1.02921524]
 [-0.5048218   2.33086951 -0.85164368]]
-0.0892864460572649


In [141]:
e = np.random.randint(3,10,size=(3,3))
print(e)

[[7 9 9]
 [3 4 8]
 [9 4 9]]


In [142]:
f = np.random.choice(7,size=10)
print(f)

[2 2 6 3 4 1 6 6 0 5]


In [143]:
g = np.random.choice([10,22,39,46],size=8)
print(g)

[39 46 22 46 22 22 10 39]


In [145]:
#linear algebra

a = np.array([[1,2],[3,4]])
eigenvalues, eigenvectors = np.linalg.eig(a)
print(eigenvalues)
print(eigenvectors)

[-0.37228132  5.37228132]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


More linear algebra for the next tuto !

In [146]:
#Load data from CSV file

data = np.loadtxt('my_file.csv', delimiter=",", dtype = np.float32)

#For more parameters (missing values,etc)
data = np.genfromtxt('my_file.csv', delimiter=",", dtype = np.float32)

OSError: my_file.csv not found.